name: Static Binaries Forge

on:
    workflow_dispatch:
        inputs:
            tool_name:
              description: 'Select what tool you want to forge'
              required: true
              type: choice
              options:
                  - socat
            target_os:
              description: 'OS - Operating System'
              required: true
              type: choice
              options:
                - linux
            target_arch:
              description: 'CPU - Architecture'
              required: true
              type: choice
              options:
                - amd64
                - arm64
                - 386
                
jobs:
    build-weapon:
        runs-on: ubuntu-latest
        steps:
            - name: 1. Clone Source Code
              uses: actions/checkout@v4

            - name: 2. Setup QEMU
              uses: docker/setup-qemu-action@v3
            
            - name: 3. Setup Docker buildx
              uses: docker/setup-buildx-action@v3
            
            - name: 4. Build tool with GHA Cache
              uses: docker/build-push-action@v5
              with:
                context: ${{ github.event.inputs.tool_name }}
                platforms: ${{ github.event.inputs.target_os }}/${{ github.event.inputs.target_arch }} 
                outputs: type=local,dest=./${{ github.event.inputs.tool_name }}_static
                cache-from: type=gha
                cache-to: type=gha,mode=max
            
            - name: 5. Package artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ github.event.inputs.tool_name }}
                path: ./${{ github.event.inputs.tool_name }}_static
                retention-days: 5