name: Static Binaries Forge

on:
    workflow_dispatch:
        inputs:
            tool_name:
                description: 'Select what tool you want to forge'
                required: true
                type: choice
                options:
                    - socat

jobs:
    build-weapon:
        runs-on: ubuntu-latest
        steps:
            - name: 1. Clone Source Code
              uses: actions/checkout@v4
            
            - name: 2. Build tool
              run: |
                cd static-binaries-project/${{ github.event.inputs.tool_name }}
                DOCKER_BUILDKIT=1 docker build -o . .
            
            - name: 3. Package artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ github.event.inputs.tool_name }}
                path: /static-binaries-project${{ github.event.inputs.tool_name }}_static
                retention-days: 5